trigger:
- main  # укажите ветку, на которой будет срабатывать пайплайн, например, main

pool:
  name: 'Default'  # указываем пул агентов 'Default'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'  # используем последнюю доступную версию Python 3
  displayName: 'Set up Python'

- checkout: self  # клонируем репозиторий

- script: |
    python -m pip install --upgrade pip  # обновляем pip
    pip install -r requirements.txt  # устанавливаем зависимости из requirements.txt
  displayName: 'Install dependencies'

- script: |
    python main.py  # запускаем main.py
  displayName: 'Run main.py'
