trigger:
- main

pool:
  name: 'Default'  

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'  
  displayName: 'Set up Python'

- checkout: self  

- script: |
    python -m pip install --upgrade pip  # обновляем pip до последней версии
  displayName: 'Upgrade pip'

- script: |
    pip install -r requirements.txt  # устанавливаем зависимости из requirements.txt
  displayName: 'Install dependencies'

- script: |
    python main.py  # запускаем main.py
  displayName: 'Run main.py'
