trigger:
- main

pool:
  name: 'Default'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
  displayName: 'Set up Python'

- checkout: self

- script: |
    python main.py
  displayName: 'Run main.py'
